### PR TITLE
Flesh out readme

### PR DESCRIPTION
**Pull request by shikokuchuo**

### CODE REVIEW

**Comment by wlandau** [comment]
@shikokuchuo, could we integrate this into https://github.com/r-releases/help/blob/main/README.md instead. I would prefer to have only README in one place, which is a big reason why I created https://github.com/r-releases/help. Anything more complicated in that in https://github.com/r-releases/r-releases would invite non-package-related pull requests, which as you have seen, would make the automation more complicated. So for the REAMDE in r-releases/r-releases, could we simply point to https://github.com/r-releases/help/blob/main/README.md?

**Comment by shikokuchuo** [comment]
Oh yes - I can't believe I missed that! I think it'd be good to change this to a simple link.
I mean if it had me confused... It seemed like a very initial readme draft as it had several links on it.

**Comment by shikokuchuo** [comment]
Please merge if you are ok with the drastically simplified version.

**Comment by wlandau** [comment]
I will write a PR to try to make this clearer.

**Comment by wlandau** [comment]
Opened #29.

**Comment by shikokuchuo** [comment]
Superseded by #29

**Pull request closed without merging**
