### PR TITLE
Add BioCor a Bioconductor package

### PR DESCRIPTION
**Pull request by llrs**
Most dependencies in Bioconductor

I see that it is already built by R-universe so I don't expect any problems here...

### CODE REVIEW

**Comment by llrs** [comment]
@wlandau The [r-release universe build failed](https://github.com/r-universe/r-releases/actions/runs/8115602533) but the [Bioconductor build works](https://bioconductor.org/checkResults/devel/bioc-LATEST/BioCor/).

However it seems that it could be built before: https://cran.dev/BioCor

**Comment by wlandau** [comment]
That's odd. Unfortunately that seems to be an R-universe-related, not an R-releases issue. R-releases just populates the universe.

**Comment by llrs** [comment]
I know, but I wanted you to know that this kind of problems will arise...
I am checking on my side if the code in the github branch is not up to date or something.

**Comment by wlandau** [comment]
I think this could a good thing for the community: more stringent checks with modern machines and workflows listed transparently at https://github.com/r-universe/workflows and https://github.com/r-universe/actions.

**Pull request merged**
